language: node_js
node_js:
  - "6"
after-script:
  - scp -o StrictHostKeyChecking=no app.js root@39.105.135.169:/home/xkl
before_install:
  - openssl aes-256-cbc -K $encrypted_a5e50feb3623_key -iv $encrypted_a5e50feb3623_iv
    -in id_rsa.enc -out id_rsa -d
  - mv id_rsa ~/.ssh -f
  - chmod 600 ~/.ssh/id_rsa
  # 配置 ssh
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp ssh_config ~/.ssh/config
